#!/usr/bin/env bash
# =============================================================================
# scripts/macos_app_build.sh — Build ViessmannPlanning.app + DMG
#
# The project path is baked into the app launcher at build time.
# The resulting .app and DMG are placed in dist/.
#
# Usage:
#   ./scripts/macos_app_build.sh           # build app + DMG
#   ./scripts/macos_app_build.sh --app-only # skip DMG
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

APP_ONLY=false
for arg in "$@"; do
    [[ "$arg" == "--app-only" ]] && APP_ONLY=true
done

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
APP_NAME="ViessmannPlanning"
BUNDLE_ID="com.viessmann-planning"
CONFIG_JSON="$PROJECT_DIR/viessmann_planning/config.json"

VERSION=$(jq -r '.version'       "$CONFIG_JSON" 2>/dev/null || echo "unknown")
CFG_PORT=$(jq -r '.ingress_port // 8098' "$CONFIG_JSON" 2>/dev/null || echo "8098")

DIST_DIR="$PROJECT_DIR/dist"
APP_DIR="$DIST_DIR/${APP_NAME}.app"
DMG_NAME="${APP_NAME}-v${VERSION}.dmg"
DMG_PATH="$DIST_DIR/${DMG_NAME}"

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
echo ""
echo -e "${CYAN}${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}${BOLD}║   viessmann-planning — macOS App Build       ║${RESET}"
echo -e "${CYAN}${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${BOLD}Version    :${RESET} ${CYAN}${VERSION}${RESET}"
echo -e "${BOLD}Project    :${RESET} ${CYAN}${PROJECT_DIR}${RESET}"
echo -e "${BOLD}Port       :${RESET} ${CYAN}${CFG_PORT}${RESET}"
echo -e "${BOLD}Output     :${RESET} ${CYAN}${DIST_DIR}${RESET}"
echo ""

# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------
if ! command -v jq >/dev/null 2>&1; then
    echo -e "${RED}✗ jq is required. Install with: brew install jq${RESET}"
    exit 1
fi

RUN_SCRIPT="$PROJECT_DIR/viessmann_planning/run.sh"
if [[ ! -f "$RUN_SCRIPT" ]]; then
    echo -e "${RED}✗ run.sh not found: ${RUN_SCRIPT}${RESET}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Clean previous build
# ---------------------------------------------------------------------------
mkdir -p "$DIST_DIR"
if [[ -d "$APP_DIR" ]]; then
    echo -e "${YELLOW}⚠ Removing previous .app...${RESET}"
    rm -rf "$APP_DIR"
fi

# ---------------------------------------------------------------------------
# .app bundle structure
# ---------------------------------------------------------------------------
echo -e "${BOLD}🔨 Building ${APP_NAME}.app...${RESET}"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# --- Info.plist ---
cat > "$APP_DIR/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>Viessmann Planning</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

plutil -lint "$APP_DIR/Contents/Info.plist" >/dev/null
echo -e "  ${GREEN}✓ Info.plist${RESET}"

# --- Launcher (project path baked in at build time) ---
cat > "$APP_DIR/Contents/MacOS/${APP_NAME}" <<LAUNCHER
#!/bin/bash
# Auto-generated by macos_app_build.sh — do not edit
PROJECT_DIR="${PROJECT_DIR}"
PORT=${CFG_PORT}

# Single-instance: if already running, just (re)open browser
if lsof -i :\${PORT} -sTCP:LISTEN >/dev/null 2>&1; then
    open "http://localhost:\${PORT}"
    exit 0
fi

# Start Flask configurator (detached from this process)
export LAUNCHED_BY_LAUNCHD=""
/bin/bash "\${PROJECT_DIR}/viessmann_planning/run.sh" --cfg \
    > "\${PROJECT_DIR}/schedules/viessmann-planning-app.log" 2>&1 &

# Wait up to 5s for Flask to be ready
for i in \$(seq 1 10); do
    sleep 0.5
    if lsof -i :\${PORT} -sTCP:LISTEN >/dev/null 2>&1; then
        open "http://localhost:\${PORT}"
        exit 0
    fi
done

osascript -e 'display alert "Viessmann Planning" message "Could not start the configurator.\nCheck that Python 3.11 is installed (brew install python@3.11)." as critical'
exit 1
LAUNCHER

chmod +x "$APP_DIR/Contents/MacOS/${APP_NAME}"
echo -e "  ${GREEN}✓ Launcher script (port ${CFG_PORT}, project: ${PROJECT_DIR})${RESET}"
echo -e "  ${GREEN}✓ .app bundle ready${RESET}"

# ---------------------------------------------------------------------------
# DMG
# ---------------------------------------------------------------------------
if [[ "$APP_ONLY" == true ]]; then
    echo ""
    echo -e "${GREEN}${BOLD}✅ Build complete (app only).${RESET}"
    echo -e "   App : ${CYAN}${APP_DIR}${RESET}"
    echo -e "   Test: ${CYAN}open '${APP_DIR}'${RESET}"
    echo ""
    exit 0
fi

echo ""
echo -e "${BOLD}📦 Creating DMG...${RESET}"

# Remove previous DMG for this version
rm -f "$DMG_PATH"

# Build DMG contents in a temp dir: app + Applications symlink
TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

cp -r "$APP_DIR" "$TMP_DIR/"
ln -sf /Applications "$TMP_DIR/Applications"

hdiutil create \
    -volname  "Viessmann Planning v${VERSION}" \
    -srcfolder "$TMP_DIR" \
    -ov \
    -format   UDZO \
    "$DMG_PATH" \
    > /dev/null

echo -e "  ${GREEN}✓ DMG created${RESET}"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
APP_SIZE=$(du -sh "$APP_DIR" | cut -f1)
DMG_SIZE=$(du -sh "$DMG_PATH" | cut -f1)

echo ""
echo -e "${GREEN}${BOLD}✅ Build complete.${RESET}"
echo -e "   App  : ${CYAN}${APP_DIR}${RESET} (${APP_SIZE})"
echo -e "   DMG  : ${CYAN}${DMG_PATH}${RESET} (${DMG_SIZE})"
echo ""
echo -e "   ${BOLD}Install:${RESET} open '${DMG_PATH}' → drag to Applications"
echo -e "   ${BOLD}Test   :${RESET} open '${APP_DIR}'"
echo ""
